version: "3"

services:

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 20s /docker-entrypoint.sh
    command: nginx -g "daemon off;"
    networks:
      - node-network
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: node-app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    image: mariadb:10.7.4
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge